[package]
name = "messageReader"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
